# PADL coursework

In [6]:
import sklearn
import matplotlib.pyplot as plt
import numpy as np

## Q1

### A

In [ ]:
data = np.loadtxt('datasets/PADL-Q11-train.csv', delimiter=',', skiprows=1)
model = ""

### B

In [17]:
data = np.loadtxt('datasets/PADL-Q12-train.csv', delimiter=',', skiprows=1)

### C

In [19]:
data = np.loadtxt('datasets/PADL-Q13-train.csv', delimiter=',', skiprows=1)

## Q2

In [28]:
data = np.loadtxt('datasets/PADL-Q2.csv', delimiter=',', skiprows=1)

## Q3

In [27]:
data = np.loadtxt('datasets/PADL-Q3.txt', delimiter=' ')

## Q4

In [37]:
data = np.genfromtxt('datasets/body_measurements.csv', delimiter=',', skip_header=1, filling_values=np.nan)
print(data)

[[0.000e+00 9.040e+02 1.000e+03 1.723e+03 6.090e+01 7.240e+02]
 [0.000e+00 8.590e+02 1.027e+03 1.694e+03 6.320e+01 6.900e+02]
 [0.000e+00 1.092e+03 1.135e+03 1.659e+03 8.500e+01 1.014e+03]
 ...
 [1.000e+00 1.077e+03 1.029e+03 1.835e+03 8.870e+01 9.670e+02]
 [0.000e+00 8.490e+02 9.260e+02 1.578e+03 4.880e+01 6.770e+02]
 [0.000e+00 8.930e+02 1.028e+03 1.690e+03 6.080e+01 8.160e+02]]


## Q5

## Q6